# Generated by Django 4.1.5 on 2023-01-16 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=256, verbose_name='Field name')),
                ('email_field', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_field', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator])),
                ('date_field', models.DateField(blank=True, null=True)),
                ('text_field', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
    ]
