# Generated by Django 4.1.5 on 2023-01-11 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Template name')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_field', models.CharField(choices=[('email', 'email'), ('date', 'date'), ('phone', 'phone'), ('text', 'text')], max_length=5, verbose_name='Field type')),
                ('name_field', models.CharField(max_length=256, verbose_name='Field name')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Example', to='myform.template', verbose_name='Template')),
            ],
        ),
    ]
