# Generated by Django 4.1.5 on 2023-01-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Example', to='myform.template', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='field',
            name='text',
            field=models.TextField(max_length=254),
        ),
    ]
