# Generated by Django 4.1.5 on 2023-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0002_alter_field_template_alter_field_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
